export enum ActionType {
    FETCH_ALL_USERS = "FETCH_ALL_USERS",
    FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE",
    AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS",
    AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE",
  }
  